default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fallacymania_development

test:
  <<: *default
  database: fallacymania_test

production:
  <<: *default
  database: fallacymania
